# Generated by Django 3.2 on 2022-08-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='long',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
