# Generated by Django 3.2 on 2022-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0002_auto_20220801_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес'),
        ),
    ]
