# Generated by Django 3.2 on 2022-07-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderingproduct_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderingproduct',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
