# Generated by Django 3.2 on 2022-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_orderingproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('preparing', 'Готовится'), ('delivering', 'В доставке'), ('ready', 'Выполнен')], db_index=True, default='new', max_length=10),
        ),
    ]
