# Generated by Django 3.2 on 2022-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('preparing', 'Готовится'), ('delivering', 'В доставке'), ('ready', 'Выполнен')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
