# Generated by Django 3.2 on 2022-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220723_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('online', 'Оплата онлайн')], db_index=True, max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
