# Generated by Django 3.2 on 2022-07-31 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_restaurants', to='foodcartapp.restaurant', verbose_name='Ресторан, готовящий заказ'),
        ),
    ]
