# Generated by Django 3.2 on 2022-08-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0001_initial'),
        ('foodcartapp', '0055_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_locations', to='geo_location.geolocation', verbose_name='Координаты заказчика'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_locations', to='geo_location.geolocation', verbose_name='Координаты ресторана'),
        ),
    ]
