# Generated by Django 3.2 on 2022-08-21 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20220821_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
