# Generated by Django 3.2 on 2022-08-21 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_orderingproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
