# Generated by Django 3.2 on 2022-08-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_alter_orderingproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcartapp.order', verbose_name='Заказанные товары'),
        ),
        migrations.AlterField(
            model_name='orderingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
