# Generated by Django 3.2 on 2022-12-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20220917_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_products', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
